@startuml Prototyp

class Client {

}

class PrototypRegistry {
    -items
    -id
    +addItem()
    +getItemById()
}

interface Prototyp {
    +name
    +id
    +config
    +creationTime
    +circularReference
    -newDate()
    +clone()
}

class ConcretePrototypA {
    +name
    +id
    +config
    +creationTime
    +circularReference
    -newDate()
    +clone()
}

class ConcretePrototypB {
    +name
    +id
    +config
    +creationTime
    +circularReference
    -newDate()
    +clone()
}

class ComponentWithBackReference {

}

Client --> PrototypRegistry
PrototypRegistry o-- Prototyp
Prototyp <|.. ConcretePrototypA
Prototyp <|.. ConcretePrototypB
ConcretePrototypA ..> ComponentWithBackReference
ConcretePrototypB ..> ComponentWithBackReference
@enduml