@startuml FactoryMethod

abstract Creator {
    +someOperation()
    {abstract} factoryMethod()
}

class ConcreteCreatorA {
    +factoryMethod()
}

class ConcreteCreatorB {
    +factoryMethod()
}

interface Product {
    +operation()
}

class ConcreteProductA {
    +operation()
}

class ConcreteProductB {
    +operation()
}

Creator <|-- ConcreteCreatorA
Creator <|-- ConcreteCreatorB
Creator ..> Product
Product <|.. ConcreteProductA
Product <|.. ConcreteProductB
@enduml